version: '3.8'

services:
  tasacion-app:
    build: .
    ports:
      - "8502:8502"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data:rw
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data: